name: 🔒 Security Vulnerability Report
description: Report a security vulnerability in neoRL-industrial-gym
title: "[SECURITY] "
labels: ["security", "vulnerability", "triage"]
assignees:
  - security-team
body:
  - type: markdown
    attributes:
      value: |
        ## Security Vulnerability Report
        
        **⚠️ IMPORTANT: For critical security issues that require immediate attention, please email security@terragon.ai instead of filing a public issue.**
        
        Thank you for helping keep neoRL-industrial-gym secure. Please provide as much detail as possible.

  - type: checkboxes
    id: security_checklist
    attributes:
      label: Security Checklist
      description: Please confirm the following before proceeding
      options:
        - label: This is not a critical vulnerability requiring immediate private disclosure
          required: true
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I have verified this affects the latest version
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How would you rate the severity of this vulnerability?
      options:
        - Low (Information disclosure, DoS with minimal impact)
        - Medium (Limited privilege escalation, significant DoS)
        - High (Remote code execution, significant data exposure)
        - Critical (System compromise, widespread impact)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this vulnerability?
      options:
        - Safety Systems (constraint validation, emergency shutdown)
        - RL Agents (policy inference, training)
        - Environment Simulation (industrial environments)
        - Data Pipeline (dataset loading, preprocessing)
        - Monitoring & Logging (MLflow, telemetry)
        - Container/Deployment (Docker, Kubernetes)
        - Dependencies (Python packages, system libraries)
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: vulnerability_description
    attributes:
      label: Vulnerability Description
      description: Provide a clear and detailed description of the vulnerability
      placeholder: |
        Describe:
        - What the vulnerability is
        - How it can be exploited
        - What systems/data are at risk
        - Any mitigating factors
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability
      placeholder: |
        1. Install neoRL-industrial-gym version X.X.X
        2. Configure environment with...
        3. Execute the following code/commands...
        4. Observe the security issue...
    validations:
      required: true

  - type: textarea
    id: proof_of_concept
    attributes:
      label: Proof of Concept
      description: Provide proof of concept code or evidence (if safe to share publicly)
      placeholder: |
        Please provide:
        - Minimal code demonstrating the issue
        - Screenshots or log outputs
        - Any other evidence of the vulnerability
        
        **Note:** Only include PoC that is safe for public disclosure

  - type: textarea
    id: impact_assessment
    attributes:
      label: Impact Assessment
      description: Describe the potential impact of this vulnerability
      placeholder: |
        Consider:
        - Industrial safety implications
        - Data confidentiality/integrity risks
        - System availability impact
        - Compliance/regulatory concerns
    validations:
      required: true

  - type: textarea
    id: environment_details
    attributes:
      label: Environment Details
      description: Provide details about the affected environment
      placeholder: |
        - neoRL-industrial-gym version: 
        - Python version: 
        - Operating System: 
        - Deployment method: (Docker, Kubernetes, bare metal, etc.)
        - Industrial environment: (if applicable)
        - Network configuration: (if relevant)

  - type: textarea
    id: suggested_mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for how to fix or mitigate this vulnerability
      placeholder: |
        Possible approaches:
        - Code changes needed
        - Configuration adjustments
        - Deployment considerations
        - Temporary workarounds

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant references (CVEs, security advisories, research papers, etc.)
      placeholder: |
        - CVE-XXXX-XXXXX
        - Similar vulnerabilities in related systems
        - Relevant security research
        - Industrial security standards (IEC 62443, etc.)

  - type: checkboxes
    id: disclosure_agreement
    attributes:
      label: Responsible Disclosure Agreement
      options:
        - label: I agree to follow responsible disclosure practices
          required: true
        - label: I will not publicly disclose details until a fix is available
          required: true
        - label: I understand this may affect industrial safety systems and will act accordingly
          required: true